receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # Tüm ağ arayüzlerinden bağlantı kabul eder
      http:
        endpoint: "0.0.0.0:4318" # Tüm ağ arayüzlerinden bağlantı kabul eder

exporters:
  otlp:
    endpoint: "jaeger:14250" # Jaeger'ın OTLP endpoint'i
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]